### ISSUE TITLE
KeyError: u'tags.sshUser'

### ISSUE THREAD

**Issue by gou1** [CiscoCloud/terraform.py#14]
Hey,

Kudos for this project, hopefully it'll replace my quick'n'dirty bash script for generating a static inventory from tf state!

I tried to use it on an existing state file for an aws-only infrastructure, but got the following error:
```
terraform.py --list
Traceback (most recent call last):
  File "terraform.py", line 545, in <module>
    main()
  File "terraform.py", line 530, in main
    output = query_list(hosts)
  File "terraform.py", line 472, in query_list
    for name, attrs, hostgroups in hosts:
  File "terraform.py", line 67, in iterhosts
    yield parser(resource, module_name)
  File "terraform.py", line 83, in inner
    name, attrs, groups = func(*args, **kwargs)
  File "terraform.py", line 322, in aws_host
    'ansible_ssh_user': raw_attrs['tags.sshUser'],
KeyError: u'tags.sshUser'
```

Maybe it's worth mentioning i don't specify in terraform and ansible the ssh user, I rely on my .ssh/config for that.

Let me know if you need more information.

**Comment by BrianHicks** [comment]
ah, that makes sense. We've been removing things specific to [Mantl](github.com/CiscoCloud/microservices-infrastructure) but apparently have missed that one! I'll patch it soon.

**Comment by gou1** [comment]
Thanks :+1: !
