### ISSUE TITLE
Output Hostfile Groupings

### ISSUE THREAD

**Issue by rossedman** [CiscoCloud/terraform.py#33]
Would it be beneficial when outputting the hosts file to be able to group through a property in Terraform? For instance, adding a tag or property to the resource would group servers in the Ansible inventory when output...

Example:

```
resource "vsphere_virtual_machine" "node" {
  count     = 3
  # other properties....
  tags {
    Name = "my-ansible-group"
  }
}
```

Output of inventory file using `terraform.py --hostfile`
```
[my-ansible-group]
192.168.99.100     node1
192.168.99.100     node2
192.168.99.100     node3
```

If this seems like a good idea, I could work on a PR.

**Comment by BrianHicks** [comment]
The code already does this, check out the groups construction for whatever flavor you're using. [Example in Digital Ocean](https://github.com/CiscoCloud/terraform.py/blob/master/terraform.py#L176-L186)

If you want to have arbitrary grouping, most of the parsers output `cloud_metadata_key=value` and groups are created that way.

We don't want to add a header in the hostfile, AFAICT it's invalid syntax. How are you using the hostfile?

**Comment by rossedman** [comment]
@BrianHicks This was related to my other PR, but was a misunderstanding. I was using the vSphere provider which I thought didn't have support for this but it does [here](https://github.com/CiscoCloud/terraform.py/blob/master/terraform.py#L478-L479).  Makes more sense now. :+1:
