### ISSUE TITLE
Add ansible 2.0 support

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/terraform.py#7]
Re: https://github.com/CiscoCloud/microservices-infrastructure/issues/529

Add support for Ansible 2.0.

**Comment by suizman** [comment]
For me it works with v2.0.0.1-1 v2.0.0.2-1 on Arch Linux in python2.7 venv

**Comment by siddharthist** [comment]
It also works in my own testing. Relevant issue in mantl is now https://github.com/CiscoCloud/microservices-infrastructure/issues/806.

**Comment by rossedman** [comment]
@siddharthist When committing the recent updates to terraform.py I used Ansible 2.0. Not sure where the problem would be, I don't believe anything changed with dynamic inventory.

@stevendborrelli Can you provide any specific use cases where 2.0 fails?

**Comment by stevendborrelli** [comment]
No, I don't have any test cases where 2.0 fails.
