### ISSUE TITLE
Add output option for a hosts file

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/terraform.py#8]
Something like `terraform.py --hostfile`. It would output the hosts between comment blocks for easy addition and removal: `terraform.py --hostfile >> /etc/hosts` should be a reasonable thing to do.

**Comment by rossedman** [comment]
:+1:  Wow, did this get implemented this is great.

**Comment by BrianHicks** [comment]
Yes, it's in now. Check the output of --help on your version for details and revisions since the original merge.

**Comment by rossedman** [comment]
@BrianHicks Worked great for me. Thanks for this.
